name:                functor-products
version:             0.1.1.0
github:              "mstksg/functor-products"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2019"
tested-with:         GHC >= 8.8

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            General functor products for various Foldable instances
category:            Data

description: |
  Generalizes the Rec type in vinyl to work over various different Foldable
  instances, instead of just lists.  Provides a unifying abstraction for all
  of them, as well as data types to index into them.

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Werror=incomplete-patterns

dependencies:
- base >= 4.13 && < 5
- microlens
- singletons >= 2.6
- text
- vinyl

library:
  source-dirs: src
